export default [
  require('assets/vault-animation/0001.png'),
  require('assets/vault-animation/0002.png'),
  require('assets/vault-animation/0003.png'),
  require('assets/vault-animation/0004.png'),
  require('assets/vault-animation/0005.png'),
  require('assets/vault-animation/0006.png'),
  require('assets/vault-animation/0007.png'),
  require('assets/vault-animation/0008.png'),
  require('assets/vault-animation/0009.png'),
  require('assets/vault-animation/0010.png'),
  require('assets/vault-animation/0011.png'),
  require('assets/vault-animation/0012.png'),
  require('assets/vault-animation/0013.png'),
  require('assets/vault-animation/0014.png'),
  require('assets/vault-animation/0015.png'),
  require('assets/vault-animation/0016.png'),
  require('assets/vault-animation/0017.png'),
  require('assets/vault-animation/0018.png'),
  require('assets/vault-animation/0019.png'),
  require('assets/vault-animation/0020.png'),
  require('assets/vault-animation/0021.png'),
  require('assets/vault-animation/0022.png'),
  require('assets/vault-animation/0023.png'),
  require('assets/vault-animation/0024.png'),
  require('assets/vault-animation/0025.png'),
  require('assets/vault-animation/0026.png'),
  require('assets/vault-animation/0027.png'),
  require('assets/vault-animation/0028.png'),
  require('assets/vault-animation/0029.png'),
  require('assets/vault-animation/0030.png'),
  require('assets/vault-animation/0031.png'),
  require('assets/vault-animation/0032.png'),
  require('assets/vault-animation/0033.png'),
  require('assets/vault-animation/0034.png'),
  require('assets/vault-animation/0035.png'),
  require('assets/vault-animation/0036.png'),
  require('assets/vault-animation/0037.png'),
  require('assets/vault-animation/0038.png'),
  require('assets/vault-animation/0039.png'),
  require('assets/vault-animation/0040.png'),
  require('assets/vault-animation/0041.png'),
  require('assets/vault-animation/0042.png'),
  require('assets/vault-animation/0043.png'),
  require('assets/vault-animation/0044.png'),
  require('assets/vault-animation/0045.png'),
  require('assets/vault-animation/0046.png'),
  require('assets/vault-animation/0047.png'),
  require('assets/vault-animation/0048.png'),
  require('assets/vault-animation/0049.png'),
  require('assets/vault-animation/0050.png'),
  require('assets/vault-animation/0051.png'),

  // require('assets/vault-animation/0052.png'),
  // require('assets/vault-animation/0053.png'),
  // require('assets/vault-animation/0054.png'),
  // require('assets/vault-animation/0055.png'),
  // require('assets/vault-animation/0056.png'),
  // require('assets/vault-animation/0057.png'),
  // require('assets/vault-animation/0058.png'),
  // require('assets/vault-animation/0059.png'),
  // require('assets/vault-animation/0060.png'),
  // require('assets/vault-animation/0061.png'),
  // require('assets/vault-animation/0062.png'),
  // require('assets/vault-animation/0063.png'),
  // require('assets/vault-animation/0064.png'),
  // require('assets/vault-animation/0065.png'),
  // require('assets/vault-animation/0066.png'),
  // require('assets/vault-animation/0067.png'),
  // require('assets/vault-animation/0068.png'),
  // require('assets/vault-animation/0069.png'),
  // require('assets/vault-animation/0070.png'),
  // require('assets/vault-animation/0071.png'),
  // require('assets/vault-animation/0072.png'),
  // require('assets/vault-animation/0073.png'),
  // require('assets/vault-animation/0074.png'),
  // require('assets/vault-animation/0075.png'),
  // require('assets/vault-animation/0076.png'),
  // require('assets/vault-animation/0077.png'),
  // require('assets/vault-animation/0078.png'),
  // require('assets/vault-animation/0079.png'),
  // require('assets/vault-animation/0080.png'),
  // require('assets/vault-animation/0081.png'),
  // require('assets/vault-animation/0082.png'),
  // require('assets/vault-animation/0083.png'),
  // require('assets/vault-animation/0084.png'),
  // require('assets/vault-animation/0085.png'),
  // require('assets/vault-animation/0086.png'),
  // require('assets/vault-animation/0087.png'),
  // require('assets/vault-animation/0088.png'),
  // require('assets/vault-animation/0089.png'),
  // require('assets/vault-animation/0090.png'),
  // require('assets/vault-animation/0091.png'),
  // require('assets/vault-animation/0092.png'),
  // require('assets/vault-animation/0093.png'),
  // require('assets/vault-animation/0094.png'),
  // require('assets/vault-animation/0095.png'),
  // require('assets/vault-animation/0096.png'),
  // require('assets/vault-animation/0097.png'),
  // require('assets/vault-animation/0098.png'),
  // require('assets/vault-animation/0099.png'),
  // require('assets/vault-animation/0100.png'),
  // require('assets/vault-animation/0101.png'),
  // require('assets/vault-animation/0102.png'),
  // require('assets/vault-animation/0103.png'),
  // require('assets/vault-animation/0104.png'),
];